### ISSUE TITLE
With flutter 2.2.3 your example doen't work

### ISSUE THREAD

**Issue by alexaccaci** [easazade/android-long-task#5]
I'm trying to run your example with flutter 2.2.3 and I'm getting this error message:E/flutter ( 7230): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'
E/flutter ( 7230): #0      AppClient.getData (package:android_long_task/long_task/app_client.dart:49:26)
E/flutter ( 7230): <asynchronous suspension>

My flutter doctor output is:
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)

• No issues found!

Best
Alex

**Comment by easazade** [comment]
thanks for reporting this issue. i have migrated it to null safety a while back and tested it on Flutter 2.2.1. I'll definitely check it out

**Comment by easazade** [comment]
@alexaccaci I didn't hit the bug myself but it was simple type casting exception. applied a fix so it won't happen again. would appreciate it if you could confirm it is fixed if your got the time

**Comment by alexaccaci** [comment]
It's ok
Best Regards

Il giorno mer 28 lug 2021 alle ore 19:57 alireza easazade <
***@***.***> ha scritto:
